# Site settings
name: Mohamed Ali
title: Mohamed Ali | Aspiring Software Engineer
description: Software developer, a hackathon enthusiast, & an aspiring entrepreneur. 
url: https://mmohamedali.github.io/webpage-test
baseurl: ""
email: sugaal@gmail.com
cover: ""
